### ISSUE TITLE
Alisa examples are not compatible with latest version of Osate (2.3.3)

### ISSUE THREAD

**Issue by paolo-crisafulli** [osate/alisa-examples#6]
Hi,

Since I started using Osate 2.3.3, I get a bunch of errors.
These errors were expected as commit message for 2187db1d97d375e6b67d6a389b55d9786dbe2147 suggests.

I have created a pull request with fixes (one of them dirty: use of a deprecated method): #5

After applying the commit of this pull request, the following errors remain and are more serious, as they make validation of end-to-end flow impossible using the latency analysis plugin:
* In project SimpleControlSystem:

Description | Resource | Path | Location | Type
---|---|---|---|---
Requirement is for Flow while verification method is not for Flow | scsimplvplan.verify | /SimpleControlSystem/alisa | line: 8 /SimpleControlSystem/alisa/scsimplvplan.verify | Verify Problem
Requirement is for Flow while verification method is not for Flow | scsimplvplan.verify | /SimpleControlSystem/alisa | line: 9 /SimpleControlSystem/alisa/scsimplvplan.verify | Verify Problem

Thank you in advance for your help.

Cheers,
Paolo

**Comment by reteprelief** [comment]
Hi Paolo,
have you updated to the latest nightly build? I discovered the issue shortly after the release of 2.3.3. The logic of a new validation check had a bug that was fixed. 
Peter

**Comment by paolo-crisafulli** [comment]
Hi Peter,
Thank you for your feedback.
Yes, Alisa works fine with nightly build n°2.3.4.v20180521-1842, I also have fetched your latest commits on alisa-examples.
Would it be possible to publish the bug fix as a maintenance release, as documented [here](http://osate.org/download-and-install.html#updating-osate) ?
Thank you very much in advance.
Paolo

**Comment by reteprelief** [comment]
We are planning the next release update for June 29.

**Comment by paolo-crisafulli** [comment]
Ok, fine, thank you.

**Comment by reteprelief** [comment]
We now maintain a separate branch for Alisa examples for each OSATE Release.
