### ISSUE TITLE
How to launch verification process in any of the examples

### ISSUE THREAD

**Issue by svenTeum** [osate/alisa-examples#7]
Hi,
I'm looking at the examples regarding verification plans for requirements.
Once the .reqspec and .verify files are there, how the verification process can be launched?
I was expecting some kind of report regarding the verification but I can't find how to get to that.

Could you provide any help?

Thanks.

**Comment by reteprelief** [comment]
As the Alisa Help under Getting Started explains you open the Assurance View under Window/Show view/others..  Alisa/Assurance view.
In that view you see the assurance cases and can invoke the verification through the context menu.

**Comment by svenTeum** [comment]
Nice, I was looking at another documentation but I hadn't looked at the OSATE help menu yet.

Thank you very much for the fast reply.
