### ISSUE TITLE
Can't find Java references in Plugins.methodregistry from AlisaPredefined

### ISSUE THREAD

**Issue by svenTeum** [osate/alisa-examples#8]
Hi,
I'm loading the AlisaPredefined example in OSATE 2.3.5 (after cloning the alisa-examples repo).

In _Plugins.methodregistry_ file, there are some methods like _ComponentMassAnalysis_ that point to
`java org.osate.anlysis.architecture.PropertyTotals.invoke`

But OSATE is showing a warning "could not find method" for that line and also the assurance plan fails with "No such method" error.

Do I have to configure anything to make that work? 

Thanks

**Comment by reteprelief** [comment]
I jumped the gun by merging a branch of the examples that goes along with OSATE 2.3.6. It will come out later this week.

**Comment by reteprelief** [comment]
You can find the version of the examples that work with OSATE 2.3.5 under the release2.3.5 branch (https://github.com/osate/alisa-examples/tree/Release2.3.5)

**Comment by svenTeum** [comment]
Nice, thank you
