### ISSUE TITLE
How to use Java functions in OSATE 2.3.6

### ISSUE THREAD

**Issue by svenTeum** [osate/alisa-examples#9]
It seems that the examples branch for OSATE 2.3.6 has all references to Java functions for verification commented out.

Is the Java support broken or can I still use Java functions in OSATE 2.3.6? I'm asking because I tried to import my working project (in 2.3.5) with an assurance case that uses only Java functions in 2.3.6 and it's not working (it's very similar to the examples).

One of the examples functions that I want to use for example:
`java vmlibrary.AircraftConsistency.consistentWeightLimit`

Edit:
I tested it in osate2-2.4.0-v20181128 and it works with that version.

Thanks

**Comment by reteprelief** [comment]
There was a bug (Issue #1638) whose fix missed the release 2.3.6 deadline by one day. Therefore, we commented out the Java based verification methods in that model branch. The master branch of the Alisa examples works with the testing release.

**Comment by svenTeum** [comment]
OK, thank you for the confirmation
